const bearer = [{ bearerAuth: [] }];
const json = { "application/json": { schema: { type: "object" } } };
const ok: Record<string, unknown> = { "200": { description: "OK", content: json } };
const accepted: Record<string, unknown> = { "202": { description: "Accepted", content: json } };
const created: Record<string, unknown> = { "201": { description: "Created", content: json } };
const empty: Record<string, unknown> = { "204": { description: "No content" } };
const error = {
  "400": { description: "Bad request" },
  "401": { description: "Unauthorized" },
  "403": { description: "Forbidden" },
  "429": { description: "Rate limited" },
  "500": { description: "Server error" },
};

function op(method: string, summary: string, secured = true, responses: Record<string, unknown> = ok) {
  return { [method]: { summary, ...(secured ? { security: bearer } : {}), responses: { ...responses, ...error } } };
}

export const openApiDocument = {
  openapi: "3.0.3",
  info: {
    title: "SubmitSense API",
    version: "1.0.0",
    description: "Versioned REST API for tenant-scoped submittal workflows. SubmitSense is assistive only and never certifies engineering work.",
  },
  servers: [{ url: "/api/v1" }],
  components: {
    securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } },
    schemas: {
      StandardError: {
        type: "object",
        required: ["requestId", "error"],
        properties: {
          requestId: { type: "string" },
          error: {
            type: "object",
            required: ["message", "diagnosticCode"],
            properties: { message: { type: "string" }, diagnosticCode: { type: "string" } },
          },
        },
      },
    },
  },
  paths: {
    "/openapi.json": op("get", "OpenAPI document", false),
    "/pricing/plans": op("get", "Public pricing plans", false),
    "/content/articles": op("get", "Published knowledge-base articles", false),
    "/content/articles/{slug}": op("get", "Published knowledge-base article", false),
    "/help": op("get", "Published contextual help", false),
    "/billing/webhooks/stripe": op("post", "Stripe billing webhook", false, accepted),
    "/integrations/webhooks/{provider}": op("post", "Integration webhook", false, accepted),
    "/auth/cognito/link-user": op("post", "Internal Cognito user link", false, created),
    "/auth/me": op("get", "Current user and tenant memberships"),
    "/auth/invitations/accept": op("post", "Accept tenant invitation", true, created),
    "/tenants/{tenantId}/session": op("get", "Tenant session"),
    "/tenants/{tenantId}/invitations": op("post", "Create tenant invitation", true, created),
    "/tenants/{tenantId}/invitations/{invitationId}/resend": op("post", "Resend tenant invitation", true, created),
    "/tenants/{tenantId}/invitations/{invitationId}/revoke": op("post", "Revoke tenant invitation"),
    "/tenants/{tenantId}/members/{userId}/deactivate": op("post", "Deactivate tenant member"),
    "/tenants/{tenantId}/members/{userId}": op("delete", "Remove tenant member"),
    "/tenants/{tenantId}/projects/{projectId}/members": op("post", "Grant project access", true, created),
    "/tenants/{tenantId}/projects/{projectId}/members/{userId}": op("delete", "Revoke project access", true, empty),
    "/tenants/{tenantId}/settings/data-use": op("patch", "Update tenant data-use consent"),
    "/tenants/{tenantId}/settings/security": op("patch", "Update tenant security settings"),
    "/tenants/{tenantId}/service-accounts": op("post", "Create service account", true, created),
    "/tenants/{tenantId}/projects/{projectId}/access": op("get", "Project access"),
    "/tenants/{tenantId}/projects": { ...op("get", "List projects"), ...op("post", "Create project", true, created) },
    "/tenants/{tenantId}/projects/search": op("get", "Search accessible projects"),
    "/tenants/{tenantId}/projects/{projectId}": { ...op("get", "Project detail"), ...op("patch", "Update project") },
    "/tenants/{tenantId}/projects/{projectId}/archive": op("post", "Archive project"),
    "/tenants/{tenantId}/projects/{projectId}/unarchive": op("post", "Unarchive project"),
    "/tenants/{tenantId}/projects/{projectId}/documents/uploads": op("post", "Initiate document upload", true, created),
    "/tenants/{tenantId}/projects/{projectId}/documents/finalize": op("post", "Finalize uploaded document", true, created),
    "/tenants/{tenantId}/projects/{projectId}/processing-jobs/{jobId}": op("get", "Document-processing job status"),
    "/tenants/{tenantId}/projects/{projectId}/spec/worksections": op("get", "Parsed spec worksections"),
    "/tenants/{tenantId}/projects/{projectId}/spec/worksections/{worksectionId}/clauses": op("get", "Parsed clauses and references"),
    "/tenants/{tenantId}/projects/{projectId}/spec/requirements": op("get", "Submittal requirements"),
    "/tenants/{tenantId}/projects/{projectId}/register-items": op("get", "List register items"),
    "/tenants/{tenantId}/projects/{projectId}/register-items/{itemId}/assignment": op("patch", "Assign register item"),
    "/tenants/{tenantId}/projects/{projectId}/register-items/{itemId}/deadline": op("patch", "Update register item deadline"),
    "/tenants/{tenantId}/projects/{projectId}/register-items/{itemId}/status": op("patch", "Transition register item status"),
    "/tenants/{tenantId}/projects/{projectId}/register-items/sign-off": op("post", "Human sign-off for exact register items"),
    "/tenants/{tenantId}/projects/{projectId}/register-items/export": op("post", "Request register export", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/physical-deliverables": op("get", "List physical deliverables"),
    "/tenants/{tenantId}/projects/{projectId}/register-items/{itemId}/physical-deliverables": op("post", "Create physical-deliverable status record", true, created),
    "/tenants/{tenantId}/projects/{projectId}/physical-deliverables/{deliverableId}": op("patch", "Update physical-deliverable status"),
    "/tenants/{tenantId}/projects/{projectId}/vendor-catalogues/uploads": op("post", "Initiate vendor-catalogue upload", true, created),
    "/tenants/{tenantId}/projects/{projectId}/vendor-catalogues": op("post", "Create vendor catalogue", true, created),
    "/tenants/{tenantId}/projects/{projectId}/vendor-catalogues/{catalogueId}/parse-status": op("get", "Vendor-catalogue parse status"),
    "/tenants/{tenantId}/vendors": { ...op("get", "List tenant vendors"), ...op("post", "Create tenant vendor", true, created) },
    "/tenants/{tenantId}/products": { ...op("get", "List tenant products"), ...op("post", "Create tenant product", true, created) },
    "/tenants/{tenantId}/products/{productId}": { ...op("get", "Product detail"), ...op("patch", "Review/correct product") },
    "/tenants/{tenantId}/products/{productId}/documents": op("get", "Product document links"),
    "/tenants/{tenantId}/projects/{projectId}/product-matches": op("get", "Product-match suggestions"),
    "/tenants/{tenantId}/projects/{projectId}/product-matches/{matchId}/accept": op("post", "Accept product match"),
    "/tenants/{tenantId}/projects/{projectId}/product-matches/{matchId}/reject": op("post", "Reject product match"),
    "/tenants/{tenantId}/projects/{projectId}/product-matches/override": op("post", "Override product match", true, created),
    "/tenants/{tenantId}/projects/{projectId}/register-items/{itemId}/product-matches/rematch": op("post", "Request product rematch", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/risk-flags/generate": op("post", "Generate rejection-risk flags", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/risk-flags/jobs/{jobId}": op("get", "Risk generation job status"),
    "/tenants/{tenantId}/projects/{projectId}/risk-flags": op("get", "List rejection-risk flags"),
    "/tenants/{tenantId}/projects/{projectId}/risk-flags/{flagId}/confirm": op("post", "Confirm rejection-risk flag"),
    "/tenants/{tenantId}/projects/{projectId}/risk-flags/{flagId}/dismiss": op("post", "Dismiss rejection-risk flag"),
    "/tenants/{tenantId}/projects/{projectId}/risk-flags/{flagId}/comment": op("post", "Comment on rejection-risk flag"),
    "/tenants/{tenantId}/projects/{projectId}/risk-flags/{flagId}/task": op("post", "Create checklist task from rejection-risk flag", true, created),
    "/tenants/{tenantId}/projects/{projectId}/risk-flags/{flagId}/rfi": op("post", "Create review-only RFI draft from rejection-risk flag", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/rfis/generate": op("post", "Generate RFI draft", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/rfis/{rfiId}": { ...op("get", "RFI draft detail"), ...op("patch", "Edit RFI draft") },
    "/tenants/{tenantId}/projects/{projectId}/rfis/{rfiId}/mark-reviewed": op("post", "Mark RFI draft reviewed"),
    "/tenants/{tenantId}/projects/{projectId}/rfis/{rfiId}/export": op("post", "Export RFI draft", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/rfis/{rfiId}/handoff": op("post", "Hand RFI draft to integration", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/packages": op("post", "Create package draft", true, created),
    "/tenants/{tenantId}/projects/{projectId}/packages/{packageId}/preview": op("get", "Preview package contents"),
    "/tenants/{tenantId}/projects/{projectId}/packages/{packageId}/items": op("post", "Add register item to package", true, created),
    "/tenants/{tenantId}/projects/{projectId}/packages/{packageId}/items/{packageItemId}": op("patch", "Update package item order, inclusion, or notes"),
    "/tenants/{tenantId}/projects/{projectId}/packages/{packageId}/items/{packageItemId}/remove": op("post", "Exclude register item from package"),
    "/tenants/{tenantId}/projects/{projectId}/packages/{packageId}/items/{packageItemId}/documents": op("post", "Attach project or tenant-library document", true, created),
    "/tenants/{tenantId}/projects/{projectId}/packages/{packageId}/versions": op("get", "List preserved package versions"),
    "/tenants/{tenantId}/projects/{projectId}/packages/{packageId}/regenerate": op("post", "Regenerate package", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/packages/{packageId}/export-pdf": op("post", "Export package PDF", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/packages/{packageId}/export-aconex": op("post", "Export Aconex-ready package bundle", true, accepted),
    "/tenants/{tenantId}/projects/{projectId}/dashboard/status": op("get", "Project status dashboard"),
    "/tenants/{tenantId}/audit-events": op("get", "Tenant audit export"),
    "/tenants/{tenantId}/projects/{projectId}/audit-events": op("get", "Project audit export"),
    "/tenants/{tenantId}/projects/{projectId}/learning-events": op("post", "Record consent-gated learning event", true, created),
    "/tenants/{tenantId}/learning-consent": { ...op("get", "Get learning-loop consent"), ...op("post", "Set learning-loop opt-in/opt-out") },
    "/tenants/{tenantId}/branding": { ...op("get", "Get package cover-sheet branding"), ...op("patch", "Update package cover-sheet branding") },
    "/tenants/{tenantId}/learning-patterns": op("get", "Anonymised, consent-gated learning-pattern aggregate"),
    "/tenants/{tenantId}/subscription": op("get", "Tenant subscription"),
    "/tenants/{tenantId}/subscription/trial": op("post", "Start tenant trial", true, created),
    "/tenants/{tenantId}/help": op("get", "Authenticated contextual help"),
    "/tenants/{tenantId}/integrations/connections": op("get", "Integration connection status"),
    "/tenants/{tenantId}/integrations/connections/{connectionId}/mappings": { ...op("get", "Integration project mappings"), ...op("post", "Create integration project mapping", true, created) },
    "/tenants/{tenantId}/integrations/connections/{connectionId}/sync-jobs": op("post", "Create integration sync job", true, accepted),
    "/tenants/{tenantId}/integrations/sync-jobs/{jobId}": op("get", "Integration sync job status"),
    "/tenants/{tenantId}/integrations/errors": op("get", "Integration errors"),
  },
};
